### ISSUE TITLE
Make network-mapper commands automatically find the network-mapper service

### ISSUE THREAD

**Issue by orishoshan** [otterize/otterize-cli#132]
Today, the `network-mapper` command looks for the network mapper Kubernetes Service in a specific namespace, `otterize-system`. If it's not there, the user must specify the namespace using --mapper-namespace.

Proposal: Make the CLI search for the Kubernetes Service using label. You will also have to update the [network mapper Helm chart](https://github.com/otterize/helm-charts/blob/main/network-mapper/templates/mapper-service.yaml) for this to work.

**Comment by markolo25** [comment]
I'll take this one
