### ISSUE TITLE
Otterize Login not taking multiple organizations in account?

### ISSUE THREAD

**Issue by victor-ufg** [otterize/otterize-cli#150]
Apparently, now that I have started using Organizations, I can't use otterize-cli? I tried using the  --org-id [Org Name] and --org-id=[Org Name], also thought of using --switch-org to no avail.

I also tried to use the actual id found in the invite link (org_xxxxxxxxxx)

`otterize login --org-id [My Org]`
will return
```
Please login to Otterize using your browser: https://auth.otterize.com/authorize?audience=https%3A%2F%2Fapp.otterize.com&client_id=[REDACTED]&redirect_uri=http%3A%2F%2Flocalhost%3A52744%2Fcallback&response_type=code&scope=openid+profile+email&state=[REDACTED]%3D
Login completed successfully! logged in as: [REDACTED]

Caution: this CLI was built with a different version/revision of the Otterize Cloud API.
Please run otterize version for more info.

Querying user info from Otterize server
Error: user belongs to multiple organizations, but no organization was specified using the X-Otterize-Organization header (HTTP error 400)
```

`otterize version`
will return
```
Version: v1.0.5
time="2024-03-07T13:25:01+01:00" level=error msg="Authentication failed: no API credentials were provided. To refresh your credentials, run 'otterize login'."
```

![image](https://github.com/otterize/otterize-cli/assets/105295869/0463e984-9008-4c04-abb4-15e2fbc78463)

**Comment by omris94** [comment]
We fixed a bug in our GraphQL API that affected login flow from the CLI for users with multiple organizations. Thank you for reporting the issue 😄
