### ISSUE TITLE
Getting error slices sortFunc usage

### ISSUE THREAD

**Issue by pavanmt** [otterize/otterize-cli#153]
Hi Team,

Seems there is a issue slices package as it is supposed to return int we are returning bool need to have a fix for this.

Getting below error could you please help me fix the issue:

# github.com/otterize/otterize-cli/src/pkg/intentsoutput
../../../../go/pkg/mod/github.com/otterize/otterize-cli@v1.0.5/src/pkg/intentsoutput/transform.go:65:27: type func(intenta v1alpha3.ClientIntents, intentb v1alpha3.ClientIntents) bool of func(intenta, intentb v1alpha3.ClientIntents) bool {…} does not match inferred type func(a v1alpha3.ClientIntents, b v1alpha3.ClientIntents) int for func(a E, b E) int
../../../../go/pkg/mod/github.com/otterize/otterize-cli@v1.0.5/src/pkg/intentsoutput/transform.go:77:45: type func(intenta v1alpha3.Intent, intentb v1alpha3.Intent) bool of func(intenta, intentb v1alpha3.Intent) bool {…} does not match inferred type func(a v1alpha3.Intent, b v1alpha3.Intent) int for func(a E, b E) int

**Comment by orishoshan** [comment]
Hey @pavanmt! This looks like a mismatch between our GitHub Actions Go version and the one in the go.mod. Will be fixed soon.
